services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CarstenWalther\T3aiCore\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Model}'

  CarstenWalther\T3aiCore\Middleware\:
    resource: '../Classes/Middleware/*'
    autowire: true
    autoconfigure: true
    public: true